[project]
name = "tiny-scraper"
version = "1.3.0"
description = "A small utility to scrape game covers for yourAnbernic RGXX devices."
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "requests==2.32.3",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.9.6",
]
